---

- import_playbook: 010_packages_install.yaml

- import_playbook: 020_cli_config.yaml

- import_playbook: 025_dev_tools.yaml

- import_playbook: 080_pihole.yaml

- import_playbook: 085_aliases.yaml
