---
- name: Installation des packages apt et snap
  hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - all_vars.yaml
  roles:
    - packages_install

- name: Set i3 config
  hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - all_vars.yaml
  tasks:
    - name: Set i3 config file
      copy:
        src: files/config
        dest: /home/{{ user }}/.config/i3/config

- name: Install oh-my-zsh
  hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - all_vars.yaml
  roles:
    - ohmyzsh_install

- name: Install docker
  hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - all_vars.yaml
  roles:
    - docker_install

- name: Install vagrant
  hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - all_vars.yaml
  roles:
    - vagrant_install